import type { Metadata } from "next";
import { PageLayout, ContentLayout } from "@/component";
import { Providers } from "./providers";
import { SideBar } from "./_SideBar";

export const metadata: Metadata = {
  title: "Battle Ground Rating",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <Providers>
          <PageLayout>
            <SideBar />
            <main>
              <ContentLayout>{children}</ContentLayout>
            </main>
          </PageLayout>
        </Providers>
      </body>
    </html>
  );
}
