import type { Metadata } from "next";
import { FiHome, FiTrendingUp, FiCompass, FiStar, FiSettings } from "react-icons/fi";
import { Box } from "@chakra-ui/react";
import { PageLayout } from "@/component";
import { Providers } from "./providers";
import { SideBar } from "./_SideBar";

export const metadata: Metadata = {
  title: "Battle Ground Rating",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <main>
          <Providers>
            <PageLayout>
              <SideBar />
              <Box ml={{ base: 0, md: 60 }} p="4">
                {children}
              </Box>
            </PageLayout>
          </Providers>
        </main>
      </body>
    </html>
  );
}
